config/routes.rb
Rails.application.routes.draw do
  resources :subscriptions do
    get :my_students, on: :collection
    member do
      get :certificate
    end
  end
  get 'users/index'
  # devise_for :users
  devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :tags, only: [:create, :index, :destroy]
  resources :courses do
    get :purchased_courses, :pending_reviews,:created_courses, :unapproved_courses, on: :collection
    member do#member means take a course i.e. self
      get :analytics
      patch :approve
      patch :unapprove
    end
    resources :lessons, except: :index do
      resources :comments, except: :index
      put :sort
      member do
        delete :delete_video
      end
    end
    resources :course_wizard, controller: 'courses/course_wizard'
    resources :subscriptions, only: [:new, :create]
  end
  
  resources :youtube, only: :show

  resources :users, only: [:index, :edit, :show, :update]
  get 'home/index'
  get 'activity', to: "home#activity"
  get 'analytics', to: "home#analytics"
  get 'privacy_policy', to: "home#privacy_policy"
  root 'home#index'

  namespace :charts do
    get 'user_per_day'
    get 'subscriptions_per_day'
    get  'course_popularity'
    get  'money_makers'
  end
  # get 'charts/user_per_day', to: "charts#user_per_day"
  # get 'charts/subscriptions_per_day', to: 'charts#subscriptions_per_day' 
  # get 'charts/course_popularity', to: "charts#course_popularity"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[ index privacy_policy]
  def index
     @latest_courses = Course.publish.approve.recent.limiter
     @my_subscriptions = Course.joins(:subscriptions).where(subscriptions: {user_id: current_user})
     @popular_courses = Course.publish.approve.popular.recent.limiter
     @top_rated_courses = Course.publish.approve.top.recent.limiter
     @reviews = Subscription.reviewed.rater.recent.limiter.order(rating: :desc)
     @popular_tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc).limit(10)
  end

  def activity
    if current_user.has_role?(:admin)
      #  @activities = PublicActivity::Activity.all.order(created_at: :desc)
      @pagy,@activities = pagy(PublicActivity::Activity.all.order(created_at: :desc))
    else
       redirect_to root_path, alert: 'Access Denied!! You are not Authorized'
    end
  end

  def analytics
    if current_user.has_role?(:admin)
      #  @user = User.all
      #  @subscriptions = Subscription.all
      #  @courses = Course.all
    else
       redirect_to root_path, alert: 'Access Denied!! You are not Authorized'
    end
  end
  

  def privacy_policy
  end
  
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/activity.html.haml
- content_for :title do
  = ULearning
  \|
  Activities
%h2
  .text-center
    Activity
    .badge.bg-secondary
      = @activities.count
%p
%ul.list-group
  - @activities.each do |activity|
    .row
    %li.list-group-item
      = activity.id
      = activity.created_at.strftime('%D - %r')
      (#{ time_ago_in_words(activity.created_at)})
      = activity.trackable_type
      = model_type(activity.trackable_type) 
      - if activity.trackable_type == 'Lesson'
        - if Lesson.where(id: activity.trackable_id).present?
          = link_to activity.trackable.title, course_lesson_path(activity.trackable.course, activity.trackable)
        - else
          was deleted
      - elsif activity.trackable_type == 'Comment'
        - if Comment.where(id: activity.trackable_id).present?
          = link_to activity.trackable.content.truncate(10, separator: ' '), course_lesson_path(activity.trackable.lesson.course, activity.trackable.lesson)
        - else
          was deleted
      - elsif activity.trackable_type == 'Subscription'
        - if Subscription.where(id: activity.trackable_id).present?
          =  activity.trackable
        - else
          was deleted
      - elsif activity.trackable_type == 'User'
        = link_to activity.trackable.email, activity.trackable if activity.trackable.present?
      - else
        = link_to activity.trackable.title, activity.trackable if activity.trackable.present?
      /= activity.key.match(/\.(.*)/)[1]
      = creative_icons(activity.key.match(/\.(.*)/)[1])
      - if activity.parameters.present?
        = activity.parameters
      by
      = link_to activity.owner.try(:username), activity.owner 
%br
!= pagy_bootstrap_nav(@pagy)

app/views/home/analytics.html.haml
%div.bg-white
  %h3.text-center.text-dark
    New users per day
  /= line_chart @user.group_by_day(:created_at).count 
  = line_chart charts_user_per_day_path
  %br
  %h3.text-center.text-dark
    Subscriptions per day
  /= column_chart @subscriptions.group_by_day(:created_at).count 
  = column_chart charts_subscriptions_per_day_path
  %br
  %h3.text-center.text-dark
    Most subscribed Courses
  /= bar_chart @subscriptions.joins(:course).group("title").count
  = bar_chart charts_course_popularity_path
  %br
  %h3.text-center.text-dark
    Money Makers
  = bar_chart charts_money_makers_path

app/views/home/index.html.haml
- content_for :title do
  = ULearning
  \|
  Home
.jumbotron.bg-light.rounded
  %h1.display-4 What do you want to learn today?
  - if user_signed_in?
    %div.pt-5
      = search_form_for @ransack_courses, as: :courses_search , url: courses_path do |f|
        .input-group
        = f.search_field :title_or_user_email_cont, placeholder: 'Find Course by Title or Author', class: 'form-control search-container'
        %span.input-group-append
          %button.btn.btn-primary.btn{:type => 'Submit'}
            %span.fa.fa-search{'aria-hidden' => 'true'}
  - else 
    %h6.text-shadow Join to access all the courses
    .p-2
    = link_to 'Register', new_user_registration_path, class: 'btn btn-success text-white'
    &nbsp;&nbsp;&nbsp;&nbsp;
    = link_to 'Login', new_user_session_path, class: 'btn btn-success text-white'
    .row.mt-1
    = link_to user_google_oauth2_omniauth_authorize_path, method: :post, class: 'btn btn-info btn-lg mr-1' do
      Continue with
      .fab.fa-google
    .row.mt-1
    = link_to user_github_omniauth_authorize_path, method: :post, class: 'btn btn-dark btn-lg mr-1' do
      Continue with
      .fab.fa-github
    .row.mt-1
    = link_to user_facebook_omniauth_authorize_path, method: :post, class: 'btn btn-primary btn-lg mr-1' do
      Continue with
      .fab.fa-facebook
%p
%div.grid2
  .card.p-4
    .card-body.p-0
    .fa.fa-graduation-cap.fa-4x
    = Course.count 
    online courses
    %p
    Explore variety of fresh courses
  .card.p-4
    .card-body.p-0
    .fa.fa-chalkboard-teacher.fa-4x
    = Course.distinct.count(:user)
    Expert Instructor
    %p
    Find the best Instructor for you
  .card.p-4
    .card-body.p-0
    .fa.fa-user-graduate.fa-4x
    = User.count 
    Active learners
    %p
    Join the online community of learners
  .card.p-4
    .card-body.p-0
    .fa.fa-infinity.fa-4x
    Life Access
    %p
    Learn at your own pace and time
%hr
- if Subscription.where(user_id: current_user).present?
  %h3.pt-2
    .fa.fa-user-graduate.text-success
    Continue Learning
  %div.grid-system
    - @my_subscriptions.each do |cour|
      = render 'courses/course', course: cour
  %p
  .texter
    = link_to 'My purchased Courses', purchased_courses_courses_path, class: 'btn btn-primary '
- elsif user_signed_in?
  %h3.text-warning
    You have Yet to subscribe to a Course
  %hr
%br
%h3.pt-2
  .fa.fa-chart-bar
  Popular Courses
%br
%div.grid-system
  - @popular_courses.each do |cour|
    = render 'courses/course', course: cour
%p
.texter
  = link_to 'More Popular Courses', courses_path(courses_search: {s: 'subscriptions_count desc'}), class: 'btn btn-primary '
%hr
%h3.pt-2
  .fa.fa-star.text-warning
  Top Courses
%br
%div.grid-system
  - @top_rated_courses.each do |cour|
    = render 'courses/course', course: cour
%p
.texter
  = link_to 'Top rated Courses', courses_path(courses_search: {s: 'average_rating desc'}), class: 'btn btn-primary '
%hr
%h3.pt-2
  .fa.fa-clock
  Latest Courses
%br
%div.grid-system
  - @latest_courses.each do |cour|
    = render 'courses/course', course: cour
%p
.texter
  = link_to 'More Recent Courses', courses_path(courses_search: {s: 'created_at desc'}), class: 'btn btn-primary '

%h3.pt-2
Popular Tags
.fa.fa-tags
%div.pt-2
  - @popular_tags.each do |tag|
    = link_to courses_path(courses_search: {course_tags_tag_id_eq: tag.id}) do
      .badge.bg-info.text-dark
        .fa.fa-tag
        = tag.name
        = tag.course_tags_count
%br
%hr
%h3.pt-2
  .fa.fa-comments
  What our students have to say?
%br
%div.grid-system
  - @reviews.each do |subscription|
    = render 'subscriptions/subscription', enrollment: subscription
%hr

app/views/home/privacy_policy.html.haml
.container
  .card.shadow
    .card-header
      %h3
        Privacy Policy
    .card-body
      %p
        Your privacy is important to us. It is u-learning's policy to respect your privacy regarding any information we may collect from you across our website,
        = succeed "," do
          %a{:href => "https://u-learning.herokuapp.com/"} u-learning
      %p We only ask for personal information when we truly need it to provide a service to you. We collect it by fair and lawful means, with your knowledge and consent. We also let you know why we’re collecting it and how it will be used.
      %p We only retain collected information for as long as necessary to provide you with your requested service. What data we store, we’ll protect within commercially acceptable means to prevent loss and theft, as well as unauthorized access, disclosure, copying, use or modification.
      %p We don’t share any personally identifying information publicly or with third-parties, except when required to by law.
      %p Our website may link to external sites that are not operated by us. Please be aware that we have no control over the content and practices of these sites, and cannot accept responsibility or liability for their respective privacy policies.
      %p You are free to refuse our request for your personal information, with the understanding that we may be unable to provide you with some of your desired services.
      %p Your continued use of our website will be regarded as acceptance of our practices around privacy and personal information. If you have any questions about how we handle user data and personal information, feel free to contact us.
      %p This policy is effective as of 8 April 2022.
%br