config/routes.rb
Rails.application.routes.draw do
  resources :subscriptions do
    get :my_students, on: :collection
    member do
      get :certificate
    end
  end
  get 'users/index'
  # devise_for :users
  devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :tags, only: [:create, :index, :destroy]
  resources :courses do
    get :purchased_courses, :pending_reviews,:created_courses, :unapproved_courses, on: :collection
    member do#member means take a course i.e. self
      get :analytics
      patch :approve
      patch :unapprove
    end
    resources :lessons, except: :index do
      resources :comments, except: :index
      put :sort
      member do
        delete :delete_video
      end
    end
    resources :course_wizard, controller: 'courses/course_wizard'
    resources :subscriptions, only: [:new, :create]
  end
  
  resources :youtube, only: :show

  resources :users, only: [:index, :edit, :show, :update]
  get 'home/index'
  get 'activity', to: "home#activity"
  get 'analytics', to: "home#analytics"
  get 'privacy_policy', to: "home#privacy_policy"
  root 'home#index'

  namespace :charts do
    get 'user_per_day'
    get 'subscriptions_per_day'
    get  'course_popularity'
    get  'money_makers'
  end
  # get 'charts/user_per_day', to: "charts#user_per_day"
  # get 'charts/subscriptions_per_day', to: 'charts#subscriptions_per_day' 
  # get 'charts/course_popularity', to: "charts#course_popularity"

end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :course, counter_cache: true# to track when a sub is deleted or added to a course
  #to update your count_cache(sub) run this in console
  # Course.find_each {|course| Course.reset_counters(course.id, :subscriptions )}
  belongs_to :user, counter_cache: true # to track when a sub is deleted or added relating to a user
    # User.find_each {|user|User.reset_counters(user.id, :subscriptions )}
  validates :user, :course, presence: true

  #this code ensures that a user subcribe to a course only once
  # hence can't subcribe to same course twice 
  validates_uniqueness_of :user_id, scope: :course_id
  validates_uniqueness_of :course_id, scope: :user_id

  #Scopes
  scope :pending_review, -> { where(rating: [0,nil, ""], review: [0,nil, ""])}
  scope :reviewed, -> { where.not(rating: [0,nil, ""], review: [0,nil, ""])}
  scope :recent, -> {order(created_at: :desc)}
  scope :limiter, -> {limit(3)}
  scope :rater, -> {order(rating: :desc)}

  validates_presence_of :rating, if: :review?
  validates_presence_of :review, if: :rating?

  extend FriendlyId
  friendly_id :to_s, use: :slugged

  def to_s
    user.username + "| "  + course.title
  end

  after_save do
    unless rating.nil? || rating.zero?
      course.update_rating
    end
  end

  # def to_s
  #   course.title + user.username
  # end

  after_destroy do
    course.update_rating
  end

  after_create :calculate_balance
  after_destroy :calculate_balance

  def calculate_balance
    course.calculate_income
    user.calculate_expenses
  end


  validate :cant_subscribe_to_own_course
  protected

  include PublicActivity::Model
  tracked owner: Proc.new{ |controller, model| controller.current_user }

  def cant_subscribe_to_own_course
    if self.new_record?
          if  self.user_id == self.course.user.id
            errors.add(:base, "You can't subscribe to your own course")
          end
    end
  end
  
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

  before_action :set_subscription, only: %i[ show edit update destroy certificate]
  before_action :set_course, only: [:new, :create ]
  # allows a non-registered user to view certificate
  skip_before_action :authenticate_user!, only: :certificate
  # GET /subscriptions or /subscriptions.json
  def index
    #  @subscriptions= Subscription.all
    @ransack_path = subscriptions_path
    @q = Subscription.ransack(params[:q])
    @pagy,@subscriptions = pagy(@q.result.includes(:user))
    authorize  @subscriptions
  end

  def my_students
    @ransack_path = my_students_subscriptions_path
    #a subscription belongs to a course hence .joins(:course) course is singular
    @q = Subscription.joins(:course).where(courses: {user_id: current_user}).ransack(params[:q])
    @pagy,@subscriptions= pagy(@q.result)
    render 'index'
  end

  # GET /subscriptions/1 or /subscriptions/1.json
  def show
  end

  def certificate
    authorize @subscription, :certificate?
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "#{@subscription.course.title}, #{@subscription.user.email}", # Excluding ".pdf" extension.
        page_size: 'A4',
        template: 'subscriptions/show.pdf.haml'
      end
    end
  end
  

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
    authorize  @subscription
  end

  # POST /subscriptions or /subscriptions.json
  def create
    if @course.price > 0
      # since stripe uses cent 13.00 == 13 and .00 cents
      @amount = (@course.price * 100).to_i
      customer = Stripe::Customer.create(
        email: params[:stripeEmail],
        source: params[:stripeToken]
      )

      charge = Stripe::Charge.create(
        customer: customer.id,
        amount: @amount, 
        description: @course.title,
        currency: 'usd'
      )
    end
    @subscription = current_user.buy_a_course(@course)
    flash[:notice] = "You have successfully subscribe to #{@course.title}"
    redirect_to course_path(@course)

    SubscriptionMailer.student_subscription(@subscription).deliver_now
    SubscriptionMailer.teacher_subscription(@subscription).deliver_now
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_course_subscription_path(@course), alert: 'Card was DECLINED'
  end

  # PATCH/PUT /subscriptions/1 or /subscriptions/1.json
  def update
    authorize  @subscription
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to subscription_url(@subscription), notice: "Subscription was successfully updated." }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1 or /subscriptions/1.json
  def destroy
      authorize  @subscription
    @subscription.destroy

    respond_to do |format|
      format.html { redirect_to subscriptions_url, alert: "Subscription was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.friendly.find(params[:id])
    end
    
    def set_course
      @course = Course.friendly.find(params[:course_id])
    end
    
    # Only allow a list of trusted parameters through.
    def subscription_params
      params.require(:subscription).permit(:review, :rating)
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@subscription) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :rating, collection: 1..5
    %p
    = f.input :review
    %p
  .form-actions
    = f.button :submit, class: 'btn btn-success'

app/views/subscriptions/_subscription.html.haml
.card.mb-2
  .card-header
    .fa.fa-user
    = link_to enrollment.user.username,enrollment.user
    .text-warning.fa.fa-clock
    = time_ago_in_words(enrollment.updated_at) + ' ago'
    .fa.fa-graduation-cap
    = link_to enrollment.course.title, enrollment.course
  - if enrollment.rating.present? || enrollment.review.present?
    .card-body
      .text-warning.fa.fa-star
      %b 
        = enrollment.rating
      %p
        .fa.fa-comment
        = enrollment.review
  - if policy(enrollment).edit?
    .card-footer
      = link_to 'Edit Review', edit_subscription_path(enrollment)

app/views/subscriptions/edit.html.haml
- content_for :title do
  U-learning
  \|
  = @subscription
.card
  .card-header
    %h1 
      .text-warning.fa.fa-star
      Add a Review
  .card-body
    = render 'form'
  .card-footer
    = link_to 'This subscription', @subscription, class: 'text-primary'
    \|
    = link_to 'Back to Courses', courses_path, class: 'text-dark'

app/views/subscriptions/index.html.haml
- content_for :title do
  ULearning
  \|
  = action_name.humanize
  Subscriptions
%h2
  .text-center
    = action_name.humanize
    Subscriptions
    .badge.bg-secondary
      = @subscriptions.size
%p
%p

= search_form_for @q, url: @ransack_path do |f|
  .row
    = f.search_field :user_email_cont, placeholder: 'Email',class:'form-control m-2', style:"width: 200px;"
    = f.search_field :rating_eq, placeholder: 'rating', class:'form-control m-2', style:"width: 200px;"
    = f.search_field :price_eq, placeholder: 'Price', class:'form-control m-2', style:"width: 200px;"
    = f.search_field :review_cont, placeholder: 'Review', class:'form-control m-2', style:"width: 200px;"
    = f.submit style:"width: 70px;", class:"btn btn-sm btn-success m-2"
%p
= link_to @ransack_path, class: 'btn btn-sm btn-info' do
  .fa.fa-sync
%p
%p
.table-responsive
  %table.table.table-bordered.table-sm.table-striped.text-white.white
    %thead
      %tr
        %th ID
        %th= sort_link(@q, :user_email, 'User')
        /.fa.fa-user
        /  /User
        %th 
          .fa.fa-graduation-cap
          Course
        %th 
          Teacher
        %th
          .fa.fa-clock
          .fa.fa-lock-open
          Bought
        %th= sort_link(@q, :price)
        /  .fa.fa-dollar-sign
        /  Price
        %th 
          .text-warning.fa.fa-clock
          Reviewed on
        %th
          .text-warning.fa.fa-comment
          Review
        %th Course Progress
        %th= sort_link(@q, :rating)
        /.text-warning.fa.fa-star
        / Rating
        %th Certificate
        %th
        %th
        %th

    %tbody.white
      - @subscriptions.each do |subscription|
        %tr.white
          %td.text-white
            = subscription.id
          %td= link_to subscription.user.username, subscription.user
          %td= link_to subscription.course.title, subscription.course
          %td= link_to subscription.course.user.username, subscription.course.user
          %td.text-white
            = subscription.created_at.strftime('%D - %r') 
          %td.text-white
            =  number_to_currency(subscription.price)
          %td.text-white
            - if subscription.rating.present?
              = subscription.updated_at.strftime('%D - %r')
          %td.text-white
            = subscription.review
          %td.text-white
            = number_to_percentage(subscription.course.progress_rate(current_user), precision: 0)
          %td.text-white
            = subscription.rating
          %td= link_to 'Certificate', certificate_subscription_path(subscription, format: :pdf), class: 'btn btn-success'
          %td= link_to 'See Review', subscription
          %td
            - if policy(subscription).edit?
              = link_to 'Add Review', edit_subscription_path(subscription), class: 'btn btn-primary'
          %td
            - if policy(subscription).destroy?
              = link_to 'Delete ', subscription, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

  %br

  = link_to "Back to Courses", courses_path
%p
  %div.text-center
    != pagy_bootstrap_nav(@pagy)

app/views/subscriptions/new.html.haml
- content_for :title do
  U-learning
  \\|
  New subscription
.card
  .card-header
    %h3
      .fa.fa-book
      = link_to @course.title, @course
      %hr/
      .fa.fa-lock-open
      Buy Course: 
      = number_to_currency(@course.price)
  .card-body
    - if @course.price > 0
      = form_tag course_subscriptions_path(@course) do
        %script.stripe-button{"data-key" => "pk_test_51KutbhE6d3rELsxa8Xa5vGwl4pekTocKkuYF70wDrcrytpekUCshVUp3KVVHtcTej4QA2qztwBcuM19oiHRK3RpZ00CskFTJup", "data-locale" => "auto", src: "https://checkout.stripe.com/checkout.js"}
    - else
      = form_tag course_subscriptions_path(@course) do
        =submit_tag "Subscribe for Free!!!", class: 'btn btn-success'
  .card-footer
    = link_to "Back to All Courses", courses_path, class: 'btn btn-primary'

app/views/subscriptions/show.html.haml
= render 'subscriptions/subscription', enrollment: @subscription

app/views/subscriptions/show.pdf.haml
%center
  %div{:style => "width:1200px; height:800px; padding:20px; text-align:center; border: 10px solid #563d7c"}
    %div{:style => "width:1150px; height:750px; padding:20px; text-align:center; border: 5px solid #563d7c"}
      %br
      %br
      %span{:style => "font-size:50px; font-weight:bold"} Certificate of Completion
  
      /%center
      /  %h1 
      /    Certificate of Completion

      %br
      %br
      %br
      %p
      %h3
        This is to certify that the owner of the email address
      %h2
        %u
          = @subscription.user.email
      %h3
        has successfully completed the course
      %h2
        %u
          = @subscription.course.title.capitalize
      %h3
        on the u-learning.herokuapp.com platform
      
      %p

      %br
      %br
      %br
      %b Certificate id: 
      #{@subscription.slug}
      
      %p
      
      %b Certificate url: 
      #{request.base_url}#{request.original_fullpath}

      %p
      %b Registration date: 
      #{@subscription.created_at.strftime('%d-%b-%Y')}
      
      %br
      %br
      %center
        %h3
          = image_tag wicked_pdf_asset_base64('life.png'), height: "30", width: "auto"
          %p
          www.u-learning.herokuapp.com