config/routes.rb
Rails.application.routes.draw do
  resources :subscriptions do
    get :my_students, on: :collection
    member do
      get :certificate
    end
  end
  get 'users/index'
  # devise_for :users
  devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :tags, only: [:create, :index, :destroy]
  resources :courses do
    get :purchased_courses, :pending_reviews,:created_courses, :unapproved_courses, on: :collection
    member do#member means take a course i.e. self
      get :analytics
      patch :approve
      patch :unapprove
    end
    resources :lessons, except: :index do
      resources :comments, except: :index
      put :sort
      member do
        delete :delete_video
      end
    end
    resources :course_wizard, controller: 'courses/course_wizard'
    resources :subscriptions, only: [:new, :create]
  end
  
  resources :youtube, only: :show

  resources :users, only: [:index, :edit, :show, :update]
  get 'home/index'
  get 'activity', to: "home#activity"
  get 'analytics', to: "home#analytics"
  get 'privacy_policy', to: "home#privacy_policy"
  root 'home#index'

  namespace :charts do
    get 'user_per_day'
    get 'subscriptions_per_day'
    get  'course_popularity'
    get  'money_makers'
  end
  # get 'charts/user_per_day', to: "charts#user_per_day"
  # get 'charts/subscriptions_per_day', to: 'charts#subscriptions_per_day' 
  # get 'charts/course_popularity', to: "charts#course_popularity"

end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course, counter_cache: true
  has_many :comments, dependent: :nullify
  #to update your count_cache(sub) run this in console
  # Course.find_each {|course| Course.reset_counters(course.id, :lessons )}
  extend FriendlyId
  friendly_id :title, use: :slugged
  has_rich_text :content
  validates :title, :content, :course, presence: true
  validates :content, length: {minimum: 10}
  validates :title, length: {minimum: 5, maximum: 50 }
  # validates :title, uniqueness: true
  validates_uniqueness_of :title, scope: :course_id
  has_many :user_lessons, dependent: :destroy

  has_one_attached :video
  validates :video, presence: true,  blob: { content_type: ['video/mp4'], size: { 
    less_than: 500.kilobytes, message: 'size should be less than 50MB'} 
  }

  has_one_attached :video_thumbnail
  validates :video_thumbnail,  blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size: { 
    less_than: 500.kilobytes, message: 'size should be less than 50MB'}
  }

  include RankedModel
  ranks :row_order, with_same: :course_id  


  include PublicActivity::Model
  tracked owner: Proc.new{ |controller, model| controller.current_user }
  
  #converting the public record to title string
  def to_s
    title
  end
  scope :recent_lessons, -> {order(created_at: :desc)}

  def lesson_viewed?(user)
    self.user_lessons.where(user_id: user).present?
  end

  def prev
    # if we are on page 2, find d last lesson less than 2 = 1
    course.lessons.where('row_order < ?', row_order).order(:row_order).last
  end

  def next
    # if we are on page 2, find d first lesson grater than 2 = 3
    course.lessons.where('row_order > ?', row_order).order(:row_order).first
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: %i[ show edit update destroy delete_video ]
  
  def sort
    @course = Course.friendly.find(params[:course_id])
    lesson = Lesson.friendly.find(params[:lesson_id])#only cos sort method is not dependent on this controller
    # Lesson.friendly.find(params[:id]) on a norms
    authorize lesson, :edit?
    lesson.update(lesson_params)
    render body: nil
  end

  def delete_video
    authorize @lesson, :edit?
    # method .purge comes from active storage doc
    @lesson.video.purge
    @lesson.video_thumbnail.purge
    redirect_to edit_course_lesson_path(@course, @lesson), alert: 'Video successfully deleted'
  end
  
  
  # GET /lessons or /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1 or /lessons/1.json
  def show
    authorize @lesson
    current_user.view(@lesson)
    @course_lessons = @course.lessons.recent_lessons.rank(:row_order)
    @comment = Comment.new
    @comments = @lesson.comments.order(created_at: :desc)
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
    @course = Course.friendly.find(params[:course_id])
    # authorize @lesson
  end

  # GET /lessons/1/edit
  def edit
    authorize @lesson
  end

  # POST /lessons or /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)
    @course = Course.friendly.find(params[:course_id])
    @lesson.course = @course 
    authorize @lesson
    respond_to do |format|
      if @lesson.save
        format.html { redirect_to course_lesson_url(@course,@lesson), notice: "Lesson was successfully created." }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1 or /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to course_lesson_url(@course, @lesson), notice: "Lesson was successfully updated." }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1 or /lessons/1.json
  def destroy
    authorize @lesson
    @lesson.destroy

    respond_to do |format|
      format.html { redirect_to course_url(@course), alert: "Lesson was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
       @course = Course.friendly.find(params[:course_id])
       @lesson = Lesson.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lesson_params
      #we didn't include "course_id" here since it was in the actions above
      #if included here, it might easy to hack
      params.require(:lesson).permit(:title, :content, :row_order_position, :video, :video_thumbnail)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.haml
-# frozen_string_literal: true
= simple_form_for([@course, @lesson]) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  %h4
    - if @lesson.new_record?
      = "For #{(Course.friendly.find(params[:course_id])).title.capitalize } Course" 
    - else
      = "For #{ (Lesson.friendly.find(params[:id]) ).course.title.capitalize } Course" 
  .form-inputs
    = f.input :title
    %br
    /= f.label :content
    /= f.rich_text_area :content
    /%small= f.error:content, class:'text-danger'
    = f.input :content, as: :rich_text_area
    %br
    - if @lesson.video.attached?
      = @lesson.video.filename
      - if policy(@lesson).edit?
        = link_to delete_video_course_lesson_path, method: :delete, data: {confirm: 'Are you sure?'} do
          .fa.fa-trash.text-danger
    = f.input :video
    %br
    - if @lesson.video_thumbnail.attached?
      = @lesson.video_thumbnail.filename
    = f.input :video_thumbnail
    %br
    /= f.input :content
    /= f.association :course
    /= f.input :course_id, input_html: {value: @lesson.course_id || params[:course_id]}, as: :hidden

  .form-actions
    = f.button :submit, class: 'btn btn-success'
  %p

app/views/lessons/_lesson.html.haml
.card
  .card-header
    - if lesson.lesson_viewed?(current_user)
      .far.fa-check-square.text-success
    - else
      .fa.fa-lock.text-warning
    = link_to lesson.title, course_lesson_path(@course, lesson)
  - if policy(lesson).show? 
    .card-body
      - if lesson.video_thumbnail.present? && lesson.video.present?
        /= image_tag(lesson.video_thumbnail, width: '500px', height: '200px')
        %video(controls = "true" poster = "#{url_for lesson.video_thumbnail}" height= '400px' width= "100%" preload= "metadata")
          %source{src: rails_blob_url(lesson.video) } 
      - elsif lesson.video.present?
        %video(controls = "true" width= "100%" preload= "metadata")
          %source{src: rails_blob_url(lesson.video) } 
      /= content_tag :video, id: 'my-video' do
      /  = tag :source, src: rails_blob_url(lesson.video)

      = lesson.content
  - if policy(lesson).edit? 
    .card-footer
      = link_to 'Edit', edit_course_lesson_path(@course,lesson), class: 'btn btn-sm btn-warning'
      = link_to 'Destroy', [@course,lesson], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'
  - if @lesson.prev.present? || @lesson.next.present?
    .card-footer
      .row
        .col-6
          - if @lesson.prev.present?
            = link_to course_lesson_path(@course, @lesson.prev), class: 'btn btn-primary' do
              .fa.fa-arrow-left
              Previous
        .col-6
          - if @lesson.next.present?
            .texter
              = link_to course_lesson_path(@course, @lesson.next), class: 'btn btn-primary' do
                Next
                .fa.fa-arrow-right

app/views/lessons/_lessons_previews.html.haml
%div.d-flex.justify-content-between
  %div
    - if lesson.lesson_viewed?(current_user)
      .far.fa-check-square.text-success
    - else
      .fa.fa-lock.text-warning
    - if lesson.row_order.present?
      = lesson.row_order_rank + 1
    = link_to lesson.title, course_lesson_path(@course,lesson)
  %div
    /unique viewers:
    - if policy(lesson).destroy?
      .fa.fa-eye
      = lesson.user_lessons.count
    .far.fa-eye
    = lesson.user_lessons.map(&:impression).sum
    .fa.fa-comment
    = lesson.comments_count

app/views/lessons/edit.html.haml
- content_for :title do
  = ULearning
  \|
  Edit 
  =  @lesson.title
.card
  .card-header
    %h1
      .fa.fa-pen
      Editing lesson
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Back to lesson', course_lesson_path(@course,@lesson)
    \|
    = link_to 'Back to Course', course_path(@lesson.course)

app/views/lessons/index.html.haml
%h1 Listing lessons

%table
  %thead
    %tr
      %th Title
      %th Content
      %th Course
      %th
      %th
      %th

  %tbody
    - @lessons.each do |lesson|
      %tr
        %td= lesson.title
        %td= lesson.content
        %td= lesson.course.title
        %td= link_to 'Show', lesson
        %td= link_to 'Edit', edit_lesson_path(lesson)
        %td= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Lesson', new_lesson_path

app/views/lessons/new.html.haml
- content_for :title do
  = ULearning
  \|
  = @course.title
  \|
  New Lesson
.card
  .card-header
    %h1
      .fa.fa-plus-circle.text-primary
      New lesson
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Back', course_path(@course)

app/views/lessons/show.html.haml
- content_for :title do
  = ULearning
  \|
  = @lesson.course.title
  \|
  = @lesson.title
= link_to 'Courses', courses_path
\/
= link_to "#{@lesson.course.title}", course_path(@lesson.course)
\/
= link_to "#{@lesson.title}", course_lesson_path(@lesson)
%p
.row
  .col-lg-8.order-1.order-lg-1
    /= @lesson.user_lessons.where(user_id: current_user).first.impression
    = render 'lessons/lesson', lesson: @lesson
    %br
    .card
      .card-header
        New Comment
      .card-body
        = render 'lessons/comments/form'
    %br
    - if @comments.present?
      .row
        %h3
          .fa.fa-comment.text-warning
          Comments:  
          /= @comments.count
          = @lesson.comments_count
        - @comments.each do |comment|
          = render 'lessons/comments/show', comment: comment
  .col-lg-4.order-0.order-lg-1
    %ul.list-group
      %li.list-group-item.list-group-item-warning
        .row
          .col-6
            .fa.fa-graduation-cap
            = link_to @course.title, @course
          .col-6
            .texter
              .fa.fa-spinner
              = number_to_percentage(@course.progress_rate(current_user), precision: 0)
      - @course_lessons.each do |lessoner|
        - if @lesson.present? && lessoner == @lesson
          %li.list-group-item.list-group-item-success
            = render 'lessons/lessons_previews', lesson: lessoner
        -else
          %li.list-group-item
            = render 'lessons/lessons_previews', lesson: lessoner