config/routes.rb
Rails.application.routes.draw do
  resources :subscriptions do
    get :my_students, on: :collection
    member do
      get :certificate
    end
  end
  get 'users/index'
  # devise_for :users
  devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :tags, only: [:create, :index, :destroy]
  resources :courses do
    get :purchased_courses, :pending_reviews,:created_courses, :unapproved_courses, on: :collection
    member do#member means take a course i.e. self
      get :analytics
      patch :approve
      patch :unapprove
    end
    resources :lessons, except: :index do
      resources :comments, except: :index
      put :sort
      member do
        delete :delete_video
      end
    end
    resources :course_wizard, controller: 'courses/course_wizard'
    resources :subscriptions, only: [:new, :create]
  end
  
  resources :youtube, only: :show

  resources :users, only: [:index, :edit, :show, :update]
  get 'home/index'
  get 'activity', to: "home#activity"
  get 'analytics', to: "home#analytics"
  get 'privacy_policy', to: "home#privacy_policy"
  root 'home#index'

  namespace :charts do
    get 'user_per_day'
    get 'subscriptions_per_day'
    get  'course_popularity'
    get  'money_makers'
  end
  # get 'charts/user_per_day', to: "charts#user_per_day"
  # get 'charts/subscriptions_per_day', to: 'charts#subscriptions_per_day' 
  # get 'charts/course_popularity', to: "charts#course_popularity"

end

app/models/course.rb
class Course < ApplicationRecord
    validates :title,:short_description,:price,:level,:language, presence: true
    validates :description,presence: true, length: {minimum: 5}
    validates :title, uniqueness: true,  length: {maximum: 50}
    validates :price, numericality: { greater_than_or_equal_to: 0 }
    has_rich_text :description
    belongs_to :user, counter_cache: true

    has_many :course_tags, dependent: :destroy
    has_many :tags, through: :course_tags
    # User.find_each {|user|User.reset_counters(user.id, :courses )}
    has_many :lessons, dependent: :destroy, inverse_of: :course
    accepts_nested_attributes_for :lessons, reject_if: :all_blank, allow_destroy: true
    # from_activestorage
    has_one_attached :avatar
    validates :avatar, presence: true, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..(2.megabytes) }

    #:restrict_with_error - a course can't be deleted if it has a subscription
    has_many :subscriptions, dependent: :restrict_with_error
    
    #a course has lessons, also checked_lessons via lessons
    #use the lesson.id to find it in the user_lessons table
    has_many :checked_lessons, through: :lessons, source: :user_lessons

    extend FriendlyId
    friendly_id :title, use: :slugged
    
    scope :recent, -> {order(created_at: :desc)}
    scope :limiter, -> {limit(3)}
    scope :popular, -> {order(subscriptions_count: :desc)}
    scope :top, -> {order(average_rating: :desc).limiter}
    scope :approve, -> {where(approved: true)}
    scope :unapprove, -> {where(approved: false)}
    scope :publish, -> {where(published: true)}
    scope :unpublish, -> {where(published: false)}
    
    LANGUAGES = [ :English, :French, :Spanish, :Russian]
    def self.languages
        LANGUAGES.each {|language| language}
    end

    LEVELS = [ :Beginner, :Intermediate, :Advanced]
    def self.levels
        LEVELS.each {|level| level}
    end
    
    include PublicActivity::Model
    tracked owner: Proc.new{ |controller, model| controller.current_user }

    def user_subscribed?(user)
        self.subscriptions.where(course_id: self.id, user_id: user.id).present?
    end

    def calculate_income
        update_column :income, (subscriptions.map(&:price).sum)
        user.calculate_balance
    end
    
    def update_rating
        if subscriptions.present? && subscriptions.where.not(rating: nil)
            update_column :average_rating, (subscriptions.average(:rating).to_f)
        else
            update_column :average_rating, (0.0)
        end
    end

    def progress_rate(user)
        unless lessons.count.zero?
          (checked_lessons.where(user_id: user).count/ self.lessons_count.to_f) * 100  
        end
    end
end

app/controllers/courses/course_wizard_controller.rb
class Courses::CourseWizardController < ApplicationController
    include Wicked::Wizard
    # before action should not be b4 the include module
  before_action :set_course, only: [:show, :finish_wizard_path, :update]
  before_action :set_progress, only: [:show, :update]
  steps :basic_info, :details, :lesson, :publish

    def show
      authorize @course, :edit?
       case step
            when :basic_info
            when :details
              @tags = Tag.all
            when :publish
            when :lesson
        end
        render_wizard
    end

    def finish_wizard_path
        authorize @course, :edit?
        course_path(@course)
    end

    def update
      authorize @course, :edit?
        case step
            when :basic_info
              @course.update(course_params)
            when :details
              @tag = Tag.all
              @course.update(course_params)
            when :publish
              @course.update(course_params)
            when :lesson
              @course.update(course_params)
            
        end
         render_wizard @course #render wizard 4 course
    end
    
     
    private
    def set_progress
        if wizard_steps.any? && wizard_steps.index(step).present?#if a current step exist
          @progress = ((wizard_steps.index(step) + 1).to_f / (wizard_steps.count).to_f * 100 )   
        else
            @progress = 0
        end
    end

    def course_params
      params.require(:course).permit(:title, :description, :short_description, :level, :published, :price, :language, :avatar, tag_ids: [])
    end

    def set_course
      @course = Course.friendly.find(params[:course_id])
    end

    
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy approve unapprove analytics]
  skip_before_action :authenticate_user!, only: :show
  # GET /courses or /courses.json
  def index
    # if params[:title]
    #   @courses = Course.where('title ILIKE ?', "%#{params[:title]}%") #case in-sensitive
    # else
      # @q = Course.ransack(params[:q])
      # @courses = @q.result.includes(:user)
      #  @ransack_courses = Course.ransack(params[:courses_search], key: :courses_search)
      # if current_user.has_role?(:admin)
        #  @courses = @ransack_courses.result.includes(:user)
          @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc).limit(10)
          @ransack_path = courses_path
          @ransack_courses = Course.recent.publish.approve.ransack(params[:courses_search], search_key: :courses_search)  
          # :course_tags, :course_tags => :tag using the through table to get a tag
          @pagy,@courses = pagy(@ransack_courses.result.includes(:user, :course_tags, :course_tags => :tag))
          
      # else
      #   redirect_to root_path, alert: 'You are not authorized'
      # end
     
    # end
  end

  # GET /courses/1 or /courses/1.json
  def show
    authorize @course
    @course_lessons = @course.lessons.recent_lessons.rank(:row_order)
    @subscriptions_reviews = @course.subscriptions.reviewed
  end

  def purchased_courses
      @ransack_path = purchased_courses_courses_path
      @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
    # @courses =  Course.joins(:subscriptions).where(subscriptions: {user_id: current_user})
    #joins is used to join tables
    ##a course has many subscriptions hence .joins(:subscriptions) subscriptions is plural
    @ransack_courses = Course.joins(:subscriptions).where(subscriptions: {user_id: current_user}).ransack(params[:courses_search])
     @pagy,@courses = pagy(@ransack_courses.result.includes(:user, :course_tags, :course_tags => :tag))
    render 'index'
  end

  def analytics
     authorize @course, :owner?
  end
  

  def pending_reviews
    @ransack_path = pending_reviews_courses_path
     @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
    #MERGE is used to add a scope here
    @ransack_courses = 
      Course.joins(:subscriptions).where(subscriptions: 
      {rating: [0,nil, ""], review: [0,nil, "", ], user_id: current_user}).ransack(params[:courses_search])
     @pagy,@courses = pagy(@ransack_courses.result.includes(:user, :course_tags, :course_tags => :tag))
    render 'index'
  end

  def created_courses
    @ransack_path = created_courses_courses_path
    @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
    @ransack_courses = Course.recent.where(user_id: current_user).ransack(params[:courses_search])
     @pagy,@courses = pagy(@ransack_courses.result.includes(:user, :course_tags, :course_tags => :tag))
    render 'index' 
  end

  def unapproved_courses
    @ransack_path = unapproved_courses_courses_path
     @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
    @ransack_courses = Course.unapprove.order(created_at: :desc).ransack(params[:courses_search])
     @pagy,@courses = pagy(@ransack_courses.result.includes(:user, :course_tags, :course_tags => :tag))
    render 'index' 
  end

  def approve
    authorize @course, :approve_policy?
    @course.update_attribute(:approved, true)
    redirect_to course_path(@course), notice: 'Course successfully approved and visible'
  end

  def unapprove
     authorize @course, :approve_policy?
    @course.update_attribute(:approved, false)
    redirect_to course_path(@course), alert: 'Course successfully unapproved and hidden'
  end
  
  # GET /courses/new
  def new
    @course = Course.new
    authorize @course
    @tags = Tag.all
  end

  # GET /courses/1/edit
  def edit
    authorize @course
    @tags = Tag.all
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)
    @course.user = current_user
 
     authorize @course

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        @tags = Tag.all
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    authorize @course
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
         @tags = Tag.all
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    authorize @course
    if @course.destroy
      respond_to do |format|
        format.html { redirect_to courses_url, alert: "Course was successfully destroyed." }
        format.json { head :no_content }
      end
    else
       redirect_to course_url, alert: "Course can't be deleted because it has a subscription" 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:title, :description, :short_description, :level, :published, :price, :language, :avatar, tag_ids: [],
        lessons_attributes: [:id, :title, :content, :_destroy])      
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
  def subscribe_button(course)
    if user_signed_in?
      if current_user == course.user
          link_to 'You created this Course, View analytics', course_path(course),class: 'text-decoration-none text-primary'
      elsif course.subscriptions.where(user_id: current_user).present?
          "<i class='fa fa-spinner text-primary'></i>".html_safe + ' ' +
          number_to_percentage(course.progress_rate(current_user), precision: 0)  + 
          "<div class = 'text-success'>You already subscribed to this course, Keep learning</div>".html_safe
      elsif course.price.zero?
          link_to 'Free', new_course_subscription_path(course), class: 'btn btn-success'
      elsif !course.price.zero?
          link_to number_to_currency(course.price), new_course_subscription_path(course), class: 'btn btn-success'
      end
    else
        link_to "Check Price", new_course_subscription_path(course), class: 'btn btn-success'
    end
      
  end
  
  def review_course(course)
    if user_signed_in?
        user_sub = current_user.subscriptions.where(course_id: course.id)
      if user_sub.present?#this is now a subscription
        #user_sub.where(rating: [0,nil, ""], review: [0,nil, ""]).present?
        if  user_sub.pending_review.present?#scope in subsription
          link_to  edit_subscription_path(user_sub.first), class: 'btn btn-primary' do
            "<i class='fa fa-star text-warning'></i>".html_safe + '' +
            "<i class='fa fa-question text-warning'></i>".html_safe + '' +
            ' Add a Review'
          end
        else
          link_to subscription_path(user_sub.first), class: 'btn btn-success' do
            "<i class='fa fa-star text-warning'></i>".html_safe + '' +
            "<i class='fa fa-check text-white'></i>".html_safe + '' + ' ' +
               "Thanks for the review!"
          end
        end
      end
    end
  end

  def certificate_button(course)
    user_sub = current_user.subscriptions.where(course_id: course.id)
    if  user_sub.any?
      if course.progress_rate(current_user) == 100
        link_to certificate_subscription_path(user_sub.first, format: :pdf), class: 'btn btn-success' do
           "<i class='fa fa-file-pdf'></i>".html_safe + ' ' +
           "Certificate of Completion"
        end
      else
        "<span class = 'nocomplete'>Complete the Course to view your Certificate</span>".html_safe
        
      end
    end
  end
end

app/views/courses/_course.html.haml
.card
  .card-header
    .fa.fa-chalkboard
    = link_to course.title, course, class: 'text-decoration-none'
  - if course.avatar.attached?
    .card-img-top
      = image_tag(course.avatar, width: '100%', height: '200px') 
  .card-footer.bg-white
    = simple_format(course.short_description)
    /= course.income
  .card-footer
    .text-center
      = subscribe_button(course)
      %p
      = review_course(course)
  .card-footer
    .row
      .col-md-6
        .fa.fa-star.text-warning
        %b 
          = course.average_rating
        (  
        .fa.fa-user-graduate
        = course.subscriptions_count  
        )
        %p
          .fa.fa-tasks
          = course.lessons_count
      .col-md-6
        .aligner
          .fa.fa-chalkboard-teacher
          = course.user.username
  .card-footer
    .far.fa-clock
    = course.created_at.strftime('%D')
  - if user_signed_in? && policy(course).owner? || user_signed_in? && policy(course).destroy? 
    .card-footer
      - if policy(course).destroy?  
        = link_to 'Delete', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn  btn-danger'
      - if policy(course).owner?
        = link_to edit_course_path(course), class: 'btn  btn-warning' do
          .fas.fa-edit
          Edit
        &nbsp;&nbsp;
        = link_to  course_course_wizard_index_path(course), class: 'btn  btn-warning' do
          .fa.fa-dragon
          Wizard
        = link_to new_course_lesson_path(course, @lesson), class: 'btn  btn-primary mt-2' do
          .fa.fa-plus
          Add a lesson
        %p
        = link_to  analytics_course_path(course), class: 'btn btn-info' do
          .fa.fa-chart-bar
          Analytics
  - if user_signed_in? &&  policy(course).edit? || user_signed_in? && policy(course).approve_policy?      
    .card-footer
      - if course.published?
        .badge.bg-success
          published
      - else
        .badge.badge-sm.bg-danger unpublished
      - if course.approved?
        .badge.bg-success  
          approved
      - else
        .badge.badge-sm.bg-danger  unapproved
  - if user_signed_in? && policy(course).approve_policy?
    .card-footer
      - if course.approved?
        = link_to 'unapprove', unapprove_course_path(course),method: :patch, class: 'btn btn-danger'
      - else
        = link_to 'approve', approve_course_path(course), method: :patch, class: 'btn btn-success'
  .card-footer
    -course.tags.each do |tag|
      .badge.bg-info.text-dark
        = tag.name
          
        

app/views/courses/_form.html.haml
= simple_form_for(@course) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    %br
    /any time you create a course with a tag, a course_tag is created with course_id and tag_id
    = f.label :tag
    = f.select :tag_ids,  @tags.pluck(:name, :id), {}, { multiple: true, class: "selectize-tags"}
    %br
    /= f.label :description
    /= f.rich_text_area :description
    /%small= f.error :description, class:'text-danger'
    = f.input :description, as: :rich_text_area
    %br
    /= f.label :avatar
    = f.input :avatar
    %br
    - if @course.avatar.attached?
      = image_tag(@course.avatar, width: '200px') 
      %p
    %br
    /= f.file_field :avatar
    /%small= f.error :avatar, class:'text-danger'
    %br
    %p
    = f.input :short_description
    %br
    = f.input :language , collection: Course.languages
    %br
    = f.input :level, collection: Course.levels
    %br
    = f.input :price
    %br
    = f.input :published
    %br
    %div
      .form-actions
      = f.button :submit, class: 'btn-success'

app/views/courses/analytics.html.haml
%div.bg-white.p-3.text-dark
  - content_for :title do
    ULearning
    \|
    = "#{@course.title} Analytics"

  = link_to 'Courses', courses_path
  |
  = link_to course_path(@course) do
    .fa.fa-graduation-cap
    = @course.title
  |
  = link_to  analytics_course_path(@course) do
    .fa.fa-chart-bar
    Analytics
  %h3
    .text-center
      Analytics for
      = @course.title
  - if @course.subscriptions.present?
    %p
    %h3 Course subscriptions per day in quantity
    = line_chart @course.subscriptions.group_by_day(:created_at).count 
    %h3 Course subscriptions per day in price
    = line_chart @course.subscriptions.group_by_day(:created_at).sum(:price)
  - else
    %h3
      Sorry, users are yet to subscribe to your course
  - if @course.lessons.present?
    %h3 Unique count (How many times a lesson was openedby a user once)
    = bar_chart @course.checked_lessons.joins(:lesson).group(:'lessons.title').count
    %h3 Impression (How many times a lesson was opened)
    = bar_chart @course.checked_lessons.joins(:lesson).group(:'lessons.title').sum(:impression)
  - else
    %h3
      You are yet to create a Lesson

app/views/courses/edit.html.haml
- content_for :title do
  ULearning
  \|
  = "Editing #{@course.title}"
.card
  .card-header
    %h1 
      .fa.fa-pen
      Editing course
  .card-body
    = render 'form'
%br

= link_to 'Show', @course
\|
= link_to 'Back', courses_path

app/views/courses/index.html.haml
- content_for :title do
  ULearning
  \|
  = action_name.humanize
  courses

%h2
  .text-center
    = action_name.humanize
    courses
    .badge.bg-secondary
      = @courses.size
%p
.row
  .col-md-2
    .card-header
      %b Filter by:
    = search_form_for @ransack_courses, as: :courses_search, url:  @ransack_path do |f|
      = f.label :title
      = f.search_field :title_cont, placeholder: 'Title', class: 'form-control form-control-sm '
      %br
      = f.label :description
      = f.search_field :short_description_cont, placeholder: 'Description', class: 'form-control form-control-sm '
      %br
      /= f.search_field :language_cont, placeholder: 'Language', class: 'form-control form-control-sm '
      = f.label :language
      = f.select :language_cont, Course.languages, include_blank: true
      %br
      = f.label :tag
      /course_tags_tag_name_cont to the course_tags table to get the tag's name
      = f.search_field :course_tags_tag_name_cont,placeholder: 'Tag name', class: 'form-control form-control-sm '
      %br
      = f.label :level
      = f.select :level_cont, Course.levels, include_blank: true
      %br
      = f.label :price
      = f.search_field :price_eq, placeholder: 'Price', class: 'form-control form-control-sm '
      %br
      = f.label :Author
      = f.search_field :user_email_cont, placeholder: 'Author Username', class: 'form-control form-control-sm '
      %br
      .row
        = sort_link(@ransack_courses, :price)
      .row
        = sort_link(@ransack_courses, :average_rating, 'Rating')
      .row
        = sort_link(@ransack_courses, :created_at, 'Latest courses')
      .row
        = sort_link(@ransack_courses, :subscriptions_count, 'Popularity')
      %br
      = f.submit class: 'btn btn-success'
    %br
    = link_to   @ransack_path, class: 'btn btn-sm btn-info' do
      .fa.fa-sync
    %br
    %br
    - @tags.each do |tag|
      /= link_to courses_path(courses_search: {course_tags_tag_id_eq: tag.id}) do
      = link_to controller: controller_name, action: action_name, courses_search: {course_tags_tag_id_eq: tag.id} do
        .badge.bg-info.text-dark
          = tag.name
          = tag.course_tags_count
  .col-md-10
    %div.grid-system
      - @courses.each do |cour|
        = render 'courses/course', course: cour
    %p
      %div.text-center
        != pagy_bootstrap_nav(@pagy)

app/views/courses/new.html.haml
- content_for :title do
  ULearning
  \|
  New Course
%div.w-50.mx-auto
.card
  .card-header
    %h1 
      .fa.fa-graduation-cap
      New course
  .card-body
    = render 'form'
= link_to 'Back', courses_path

app/views/courses/show.html.haml
- content_for :title do
  = ULearning
  \|
  = @course.title

%p
.row
  .col-lg-8.order-1.order-lg-1
    %div.p-5.bg-secondary.text-white.rounded
      %h3.pb-2
        .fa.fa-graduation-cap
        =  @course.title
      %p
        .fa.fa-clock
        = @course.updated_at.strftime('%D')
      %p
        .fa.fa-globe-africa
        = @course.language
      %p
      .fa.fa-signal
      = @course.level
      %p
        /= @course.avatar.attached?
        /- if @course.avatar.attached?
        /  = image_tag(@course.avatar, width: '200px') 
      %p
        = @course.description
    %p
      %br
      - if  @course_lessons.present?
        %h3
          .row
            .col-6
              .fa.fa-tasks
              = pluralize(@course_lessons.count, 'Lesson')
            .col-6
              .texter
                .fa.fa-spinner
                = number_to_percentage(@course.progress_rate(current_user), precision: 0)
                = certificate_button(@course)
        %ul.list-group.lesson-sortable
          - @course_lessons.each do |lesson|
            = content_tag "div", id: "lesson-#{lesson.id}", data: { model_name: lesson.class.name.underscore, update_url: course_lesson_sort_path(@course, lesson)} do
              %li.list-group-item
                = render 'lessons/lessons_previews', lesson: lesson
          %p
          %h3.pt-2
            .fa.fa-comment.text-warning
            = pluralize(@course.subscriptions.reviewed.count, 'Review')
          - @subscriptions_reviews.each do |subscription|
            = render 'subscriptions/subscription', enrollment: subscription
      - else
        %h3
          The course has no Lessons yet
  .col-lg-4.order-0.order-lg-1.sticker
    .sticky-top
      = render 'courses/course', course: @course
%p